import type { ComponentProps } from "react";
import {
  Activity,
  ArrowUp,
  Award,
  Bath,
  Bell,
  Bomb,
  BookOpen,
  Brain,
  CalendarDays,
  ChartColumn,
  ChartNoAxesColumn,
  Check,
  ChevronRight,
  CircleCheck,
  CircleDashed,
  CircleQuestionMark,
  Clock3,
  CloudRain,
  Crown,
  Droplet,
  Dumbbell,
  Eye,
  Flame,
  Flower2,
  Footprints,
  Gamepad2,
  FaceAngry,
  FaceSlightlyFrowning,
  Gauge,
  Gem,
  GlassWater,
  GraduationCap,
  Handshake,
  Heart,
  House,
  Leaf,
  Lightbulb,
  Lock,
  LogOut,
  Medal,
  Moon,
  Music,
  NotebookPen,
  Palette,
  PenLine,
  PersonStanding,
  Phone,
  Plus,
  Puzzle,
  RefreshCw,
  Salad,
  ScanFace,
  Search,
  Settings,
  ShieldAlert,
  ShieldCheck,
  ShowerHead,
  Smartphone,
  Sparkles,
  Sprout,
  Star,
  Sword,
  Swords,
  Target,
  TreePine,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Utensils,
  User,
  Users,
  Wind,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react-native";
import { AppDesignTokens } from "@/constants/AppDesignTokens";

export const appIconComponents = {
  activity: Activity,
  alert: CircleQuestionMark,
  angry: FaceAngry,
  award: Award,
  bath: Bath,
  bell: Bell,
  bomb: Bomb,
  book: BookOpen,
  brain: Brain,
  calendar: CalendarDays,
  chart: ChartColumn,
  check: Check,
  "check-circle": CircleCheck,
  "chevron-right": ChevronRight,
  clock: Clock3,
  "cloud-rain": CloudRain,
  close: X,
  crown: Crown,
  "dashed-circle": CircleDashed,
  droplet: Droplet,
  dumbbell: Dumbbell,
  eye: Eye,
  flame: Flame,
  flower: Flower2,
  footprints: Footprints,
  gamepad: Gamepad2,
  frown: FaceSlightlyFrowning,
  gauge: Gauge,
  gem: Gem,
  "glass-water": GlassWater,
  graduation: GraduationCap,
  handshake: Handshake,
  heart: Heart,
  home: House,
  leaf: Leaf,
  lightbulb: Lightbulb,
  lock: Lock,
  logout: LogOut,
  medal: Medal,
  moon: Moon,
  music: Music,
  notebook: NotebookPen,
  palette: Palette,
  pen: PenLine,
  person: PersonStanding,
  phone: Phone,
  plus: Plus,
  progress: ChartNoAxesColumn,
  puzzle: Puzzle,
  refresh: RefreshCw,
  salad: Salad,
  scan: ScanFace,
  search: Search,
  settings: Settings,
  shield: ShieldCheck,
  "shield-alert": ShieldAlert,
  shower: ShowerHead,
  smartphone: Smartphone,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  sword: Sword,
  swords: Swords,
  target: Target,
  tree: TreePine,
  "trend-down": TrendingDown,
  "trend-up": TrendingUp,
  trophy: Trophy,
  utensils: Utensils,
  user: User,
  users: Users,
  warning: TriangleAlert,
  wind: Wind,
  "arrow-up": ArrowUp,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type AppIconName = keyof typeof appIconComponents;

const legacyIconNames: Record<string, AppIconName> = {
  "⚡": "zap",
  "💪": "dumbbell",
  "🧠": "brain",
  "🏃": "person",
  "📚": "book",
  "📖": "book",
  "🧘": "flower",
  "💧": "droplet",
  "🥗": "salad",
  "😴": "moon",
  "🎯": "target",
  "✍️": "pen",
  "📝": "notebook",
  "🎵": "music",
  "🏋️": "dumbbell",
  "🎨": "palette",
  "🧩": "puzzle",
  "🌿": "leaf",
  "💎": "gem",
  "🔔": "bell",
  "🛁": "bath",
  "📱": "smartphone",
  "🔥": "flame",
  "😰": "shield-alert",
  "😤": "angry",
  "😡": "angry",
  "😢": "cloud-rain",
  "💥": "bomb",
  "🌙": "moon",
  "👥": "users",
  "❓": "alert",
  "😨": "shield-alert",
  "😳": "eye",
  "😵": "refresh",
  "😶": "dashed-circle",
  "😱": "warning",
  "😞": "frown",
  "🤝": "handshake",
  "🌅": "sparkles",
  "🌱": "sprout",
  "🌲": "tree",
  "🌳": "tree",
  "👑": "crown",
  "📊": "chart",
  "📈": "trend-up",
  "📉": "trend-down",
  "🏆": "trophy",
  "🎖️": "medal",
  "🛡️": "shield",
  "⚔️": "swords",
  "🗡️": "sword",
  "✅": "check-circle",
  "🌟": "star",
  "⭐": "star",
  "🔄": "refresh",
  "💡": "lightbulb",
  "⬆️": "arrow-up",
  "💫": "sparkles",
  "🔒": "lock",
  "🚨": "shield-alert",
  "🤸": "person",
  "🌬️": "wind",
  "🙏": "heart",
  "🚿": "shower",
  "📵": "smartphone",
  "🧴": "scan",
  "🪥": "sparkles",
  "🚭": "shield",
  "🍷": "glass-water",
  "💆": "heart",
};

export function normalizeAppIconName(value: string | undefined, fallback: AppIconName = "sparkles"): AppIconName {
  if (!value) return fallback;
  if (value in appIconComponents) return value as AppIconName;
  return legacyIconNames[value] ?? fallback;
}

const notificationGlyphs: Partial<Record<AppIconName, string>> = {
  award: "★",
  check: "✓",
  "check-circle": "✓",
  flame: "◆",
  shield: "◆",
  sparkles: "✦",
  star: "★",
  trophy: "★",
  warning: "!",
  zap: "✦",
};

export function iconNotificationGlyph(value: string | undefined): string {
  const normalized = normalizeAppIconName(value);
  return notificationGlyphs[normalized] ?? "•";
}

type LucideProps = ComponentProps<LucideIcon>;

type AppIconProps = Omit<LucideProps, "name"> & {
  name: AppIconName | string;
  decorative?: boolean;
};

export function AppIcon({
  name,
  color = AppDesignTokens.colors.text,
  size = AppDesignTokens.icons.sizeMd,
  strokeWidth = AppDesignTokens.icons.strokeWidth,
  decorative = true,
  accessibilityLabel,
  ...props
}: AppIconProps) {
  const Icon = appIconComponents[normalizeAppIconName(name)];

  return (
    <Icon
      color={color}
      size={size}
      strokeWidth={strokeWidth}
      accessible={!decorative}
      accessibilityLabel={decorative ? undefined : accessibilityLabel}
      {...props}
    />
  );
}
